import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/components/Nav/Nav';

export const metadata: Metadata = {
	title: 'Idea 💡',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body cz-shortcut-listen='true'>
				<div className='maxW'>
					<Nav />
					{children}
				</div>
			</body>
		</html>
	);
}
